# Generated by Django 5.0.2 on 2024-03-22 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='damages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='latest_safety_rating',
            field=models.CharField(choices=[('Safe for use', 'Safe for use'), ('Unfit to drive on roads', 'Unfit to drive on roads')], default='Safe for use', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturing_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
