# Generated by Django 5.0.2 on 2024-03-23 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='country',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='country_code',
        ),
    ]
