# Generated by Django 5.0.2 on 2024-03-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_signup_country_remove_signup_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AddField(
            model_name='car',
            name='car_color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('white', 'White')], default='black', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='car_status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='car_color',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='not paid', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='rent_price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_car_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='total_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='user_email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
